version: "2"
services:
  web:
    build: ./composetest
    container_name: app
    ports:
      - "5000:5000"
    environment:
      SHOW: 'true'
  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/data
volumes:
  redis_data:
    